name: "build"
on:
  pull_request:
  push:
    branches:
      - master
      - development

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm install
    - run: npm run test
    - run: npm run build
